#!/bin/bash
# This script is used to check the functionality of the onboard sensors of
# the Moitessier HAT.
# Depending on your hardware you might not have all of the sensors populated.

echo "********** MS5607-02BA03 **********"
./MS5607-02BA03 &
sleep 3
pid=$(pidof MS5607-02BA03)
kill -9 $pid
echo "********** MPU-9250 **********"
./MPU-9250 &
sleep 3
pid=$(pidof MPU-9250)
kill -9 $pid
echo "********** Si7020-A20 **********"
./Si7020-A20 &
sleep 3
pid=$(pidof Si7020-A20)
kill -9 $pid

